# Generated by Django 5.2.7 on 2025-11-21 06:31

import gym_bud_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bud_app', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', gym_bud_app.models.CustomUserManager()),
            ],
        ),
    ]
