# Generated by Django 5.2.7 on 2025-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bud_app', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/du238xjtt/image/upload/v1763757297/avatar_juw0bq.svg', null=True, upload_to='avatars/'),
        ),
    ]
